export const topRatedMovies = [
  {
    adult: false,
    backdrop_path: "/5hNcsnMkwU2LknLoru73c76el3z.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 31.461,
    poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.7,
    vote_count: 3436,
  },
  {
    adult: false,
    backdrop_path: "/wPU78OPN4BYEgWYdXyg0phMee64.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 79.021,
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 20815,
  },
  {
    adult: false,
    backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 95.051,
    poster_path: "/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.7,
    vote_count: 15527,
  },
  {
    adult: false,
    backdrop_path: "/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg",
    genre_ids: [10749, 18],
    id: 730154,
    original_language: "ja",
    original_title: "きみの瞳が問いかけている",
    overview:
      "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
    popularity: 11.595,
    poster_path: "/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg",
    release_date: "2020-10-23",
    title: "Your Eyes Tell",
    video: false,
    vote_average: 8.7,
    vote_count: 246,
  },
  {
    adult: false,
    backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 45.151,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-11-30",
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 12418,
  },
  {
    adult: false,
    backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
    genre_ids: [10749],
    id: 724089,
    original_language: "en",
    original_title: "Gabriel's Inferno Part II",
    overview:
      "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
    popularity: 12.899,
    poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
    release_date: "2020-07-31",
    title: "Gabriel's Inferno Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 1387,
  },
  {
    adult: false,
    backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather: Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 57.183,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather: Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 9353,
  },
  {
    adult: false,
    backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
    genre_ids: [10749],
    id: 696374,
    original_language: "en",
    original_title: "Gabriel's Inferno",
    overview:
      "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
    popularity: 10.349,
    poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
    release_date: "2020-05-29",
    title: "Gabriel's Inferno",
    video: false,
    vote_average: 8.6,
    vote_count: 2206,
  },
  {
    adult: false,
    backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
    genre_ids: [10749, 35],
    id: 761053,
    original_language: "en",
    original_title: "Gabriel's Inferno Part III",
    overview:
      "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
    popularity: 21.478,
    poster_path: "/uqmTxOP3gNl5MWRt1wlrUnzTphM.jpg",
    release_date: "2020-11-19",
    title: "Gabriel's Inferno Part III",
    video: false,
    vote_average: 8.6,
    vote_count: 945,
  },
  {
    adult: false,
    backdrop_path: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    genre_ids: [10749, 16],
    id: 372754,
    original_language: "ja",
    original_title: "同級生",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
    popularity: 19.737,
    poster_path: "/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
    release_date: "2016-02-20",
    title: "Dou kyu sei – Classmates",
    video: false,
    vote_average: 8.6,
    vote_count: 206,
  },
  {
    adult: false,
    backdrop_path: "/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
    genre_ids: [10749, 16, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 154.442,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.5,
    vote_count: 8385,
  },
  {
    adult: false,
    backdrop_path: "/hZth9NCeXvvO7Xi98d8q34e1Ier.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 81.021,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.5,
    vote_count: 12481,
  },
  {
    adult: false,
    backdrop_path: "/l5K9elugftlcyIHHm4nylvsn26X.jpg",
    genre_ids: [18],
    id: 255709,
    original_language: "ko",
    original_title: "소원",
    overview:
      "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
    popularity: 22.943,
    poster_path: "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
    release_date: "2013-10-02",
    title: "Hope",
    video: false,
    vote_average: 8.5,
    vote_count: 318,
  },
  {
    adult: false,
    backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 88.402,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.5,
    vote_count: 13173,
  },
  {
    adult: false,
    backdrop_path: "/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg",
    genre_ids: [16, 18, 10402, 10749],
    id: 632632,
    original_language: "ja",
    original_title: "映画 ギヴン",
    overview:
      "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
    popularity: 122.95,
    poster_path: "/xKCtoYHUyX8zAg68eemnYa2orep.jpg",
    release_date: "2020-08-22",
    title: "Given",
    video: false,
    vote_average: 8.5,
    vote_count: 296,
  },
  {
    adult: false,
    backdrop_path: "/1EAxNqdkVnp48a7NUuNBHGflowM.jpg",
    genre_ids: [16, 28, 878, 18],
    id: 283566,
    original_language: "ja",
    original_title: "シン・エヴァンゲリオン劇場版:||",
    overview:
      "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
    popularity: 167.992,
    poster_path: "/md5wZRRj8biHrGtyitgBZo7674t.jpg",
    release_date: "2021-03-08",
    title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
    video: false,
    vote_average: 8.5,
    vote_count: 462,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 36.245,
    poster_path: "/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.5,
    vote_count: 6199,
  },
  {
    adult: false,
    backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 85.691,
    poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.5,
    vote_count: 13540,
  },
  {
    adult: false,
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 87.304,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-14",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 26892,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 62.855,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.5,
    vote_count: 22683,
  },
];

export const popularMovies = [
  {
    adult: false,
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 6575.499,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.3,
    vote_count: 8293,
  },
  {
    adult: false,
    backdrop_path: "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
    genre_ids: [28, 12, 53, 10752],
    id: 476669,
    original_language: "en",
    original_title: "The King's Man",
    overview:
      "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
    popularity: 3305.255,
    poster_path: "/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
    release_date: "2021-12-22",
    title: "The King's Man",
    video: false,
    vote_average: 7.1,
    vote_count: 1355,
  },
  {
    adult: false,
    backdrop_path: "/usaZV7KB6Man9Rm9TyDAeQf7uVD.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 3096.976,
    poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    release_date: "2022-01-12",
    title: "Scream",
    video: false,
    vote_average: 7,
    vote_count: 632,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 3005.145,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.8,
    vote_count: 4646,
  },
  {
    adult: false,
    backdrop_path: "/mqDnDhG5N6fn1H4MKQqr8E5wfeK.jpg",
    genre_ids: [80, 18, 53],
    id: 597208,
    original_language: "en",
    original_title: "Nightmare Alley",
    overview:
      "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
    popularity: 2703.429,
    poster_path: "/680klE0dIreQQOyWKFgNnCAJtws.jpg",
    release_date: "2021-12-02",
    title: "Nightmare Alley",
    video: false,
    vote_average: 7.2,
    vote_count: 827,
  },
  {
    adult: false,
    backdrop_path: "/mruT954ve6P1zquaRs6XG0hA5k9.jpg",
    genre_ids: [53],
    id: 800510,
    original_language: "en",
    original_title: "Kimi",
    overview:
      "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
    popularity: 2653.423,
    poster_path: "/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
    release_date: "2022-02-10",
    title: "Kimi",
    video: false,
    vote_average: 6.3,
    vote_count: 137,
  },
  {
    adult: false,
    backdrop_path: "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
    genre_ids: [16, 28, 14, 12],
    id: 768744,
    original_language: "ja",
    original_title:
      "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
    overview:
      "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.",
    popularity: 1974.726,
    poster_path: "/4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg",
    release_date: "2021-08-06",
    title: "My Hero Academia: World Heroes' Mission",
    video: false,
    vote_average: 7.4,
    vote_count: 75,
  },
  {
    adult: false,
    backdrop_path: "/qlPbDersJDdeBORrENQjoz9JfwJ.jpg",
    genre_ids: [28, 35, 80, 10749, 53],
    id: 783461,
    original_language: "hi",
    original_title: "लूप लपेटा",
    overview:
      "When her boyfriend loses a mobster's cash, Savi races against the clock to save the day — if only she can break out of a curious cycle of dead ends.",
    popularity: 1836.561,
    poster_path: "/mtLk7vugGWtMkO913Fg8zfM1YET.jpg",
    release_date: "2022-02-04",
    title: "Looop Lapeta",
    video: false,
    vote_average: 5.7,
    vote_count: 17,
  },
  {
    adult: false,
    backdrop_path: "/eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 774825,
    original_language: "en",
    original_title: "The Ice Age Adventures of Buck Wild",
    overview:
      "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
    popularity: 2155.757,
    poster_path: "/zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg",
    release_date: "2022-01-28",
    title: "The Ice Age Adventures of Buck Wild",
    video: false,
    vote_average: 7.2,
    vote_count: 626,
  },
  {
    adult: false,
    backdrop_path: "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 524434,
    original_language: "en",
    original_title: "Eternals",
    overview:
      "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
    popularity: 1836.775,
    poster_path: "/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
    release_date: "2021-11-03",
    title: "Eternals",
    video: false,
    vote_average: 7.2,
    vote_count: 4498,
  },
  {
    adult: false,
    backdrop_path: "/eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg",
    genre_ids: [53],
    id: 803114,
    original_language: "en",
    original_title: "The Requin",
    overview:
      "A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.",
    popularity: 1850.505,
    poster_path: "/i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg",
    release_date: "2022-01-28",
    title: "The Requin",
    video: false,
    vote_average: 4.5,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
    genre_ids: [28, 35, 80, 53],
    id: 512195,
    original_language: "en",
    original_title: "Red Notice",
    overview:
      "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
    popularity: 1549.538,
    poster_path: "/wdE6ewaKZHr62bLqCn7A2DiGShm.jpg",
    release_date: "2021-11-04",
    title: "Red Notice",
    video: false,
    vote_average: 6.8,
    vote_count: 3087,
  },
  {
    adult: false,
    backdrop_path: "/qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
    genre_ids: [16, 10751, 14, 35, 12],
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 1711.634,
    poster_path: "/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    release_date: "2022-02-25",
    title: "Hotel Transylvania: Transformania",
    video: false,
    vote_average: 7.5,
    vote_count: 1870,
  },
  {
    adult: false,
    backdrop_path: "/koaxq5QbARIlfxCOR89atPHv367.jpg",
    genre_ids: [35, 10749, 10402],
    id: 615904,
    original_language: "en",
    original_title: "Marry Me",
    overview:
      "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
    popularity: 1422.061,
    poster_path: "/ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
    release_date: "2022-02-09",
    title: "Marry Me",
    video: false,
    vote_average: 7,
    vote_count: 181,
  },
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [35, 16, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    popularity: 1422.806,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.2,
    vote_count: 1987,
  },
  {
    adult: false,
    backdrop_path: "/t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
    genre_ids: [28, 53],
    id: 860623,
    original_language: "en",
    original_title: "Last Man Down",
    overview:
      "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
    popularity: 1298.044,
    poster_path: "/4B7liCxNCZIZGONmAMkCnxVlZQV.jpg",
    release_date: "2021-10-19",
    title: "Last Man Down",
    video: false,
    vote_average: 6.4,
    vote_count: 276,
  },
  {
    adult: false,
    backdrop_path: "/cTTggc927lEPCMsWUsdugSj6wAY.jpg",
    genre_ids: [28, 12],
    id: 335787,
    original_language: "en",
    original_title: "Uncharted",
    overview:
      "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    popularity: 1138.486,
    poster_path: "/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
    release_date: "2022-02-10",
    title: "Uncharted",
    video: false,
    vote_average: 7.2,
    vote_count: 421,
  },
  {
    adult: false,
    backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
    genre_ids: [14, 35, 12],
    id: 425909,
    original_language: "en",
    original_title: "Ghostbusters: Afterlife",
    overview:
      "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
    popularity: 1189.293,
    poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
    release_date: "2021-11-11",
    title: "Ghostbusters: Afterlife",
    video: false,
    vote_average: 7.7,
    vote_count: 2092,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
    popularity: 1245.996,
    poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
    release_date: "2021-09-30",
    title: "Venom: Let There Be Carnage",
    video: false,
    vote_average: 7.1,
    vote_count: 6410,
  },
  {
    adult: false,
    backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    id: 460458,
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    overview:
      "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
    popularity: 1074.465,
    poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
    release_date: "2021-11-24",
    title: "Resident Evil: Welcome to Raccoon City",
    video: false,
    vote_average: 6.2,
    vote_count: 1254,
  },
];

export const upcomingMovies = [
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [35, 16, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    popularity: 1422.806,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.2,
    vote_count: 1987,
  },
  {
    adult: false,
    backdrop_path: "/cTTggc927lEPCMsWUsdugSj6wAY.jpg",
    genre_ids: [28, 12],
    id: 335787,
    original_language: "en",
    original_title: "Uncharted",
    overview:
      "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    popularity: 1138.486,
    poster_path: "/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
    release_date: "2022-02-10",
    title: "Uncharted",
    video: false,
    vote_average: 7.2,
    vote_count: 421,
  },
  {
    adult: false,
    backdrop_path: "/rvtdN5XkWAfGX6xDuPL6yYS2seK.jpg",
    genre_ids: [28, 80, 18],
    id: 414906,
    original_language: "en",
    original_title: "The Batman",
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    popularity: 428.068,
    poster_path: "/3VFI3zbuNhXzx7dIbYdmvBLekyB.jpg",
    release_date: "2022-03-01",
    title: "The Batman",
    video: false,
    vote_average: 6.3,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/iMFDOpE52wbT9GXYTvv4Em6QDhl.jpg",
    genre_ids: [16, 10751, 35, 14],
    id: 508947,
    original_language: "en",
    original_title: "Turning Red",
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 315.789,
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    release_date: "2022-03-10",
    title: "Turning Red",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/vywOsCtQfZijVLMpde4tqD7Gloi.jpg",
    genre_ids: [28, 35, 99],
    id: 656663,
    original_language: "en",
    original_title: "Jackass Forever",
    overview:
      "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
    popularity: 189.954,
    poster_path: "/ruHDFumJfW7F2vEqTZEQQ9xT7CA.jpg",
    release_date: "2022-02-01",
    title: "Jackass Forever",
    video: false,
    vote_average: 7.1,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: "/9OE62lhp5FPNJMfKXodegVLjHUA.jpg",
    genre_ids: [16, 10751],
    id: 823609,
    original_language: "en",
    original_title: "Monster Family 2",
    overview:
      "To free Baba Yaga and Renfield from the clutches of Monster Hunter Mila Starr, the Wishbone Family once more transforms into a Vampire, Frankenstein's Monster, a Mummy and a Werewolf. Aided and abetted by their three pet bats, our Monster Family zooms around the world again to save their friends, make new monstrous acquaintances and finally come to the realization that ‘Nobody’s Perfect’ – even those with flaws can find happiness.",
    popularity: 192.398,
    poster_path: "/em2NLSbVj49NjpdqmaKYuqKYZET.jpg",
    release_date: "2021-01-13",
    title: "Monster Family 2",
    video: false,
    vote_average: 7.1,
    vote_count: 28,
  },
  {
    adult: false,
    backdrop_path: "/hB4ibOHXm1Xl0IbuYVioktDGUWJ.jpg",
    genre_ids: [18, 35],
    id: 718032,
    original_language: "en",
    original_title: "Licorice Pizza",
    overview:
      "The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.",
    popularity: 149.683,
    poster_path: "/jD98aUKHQZNAmrk0wQQ9wmNQPnP.jpg",
    release_date: "2021-11-26",
    title: "Licorice Pizza",
    video: false,
    vote_average: 7.1,
    vote_count: 355,
  },
  {
    adult: false,
    backdrop_path: "/fbTxsnJcQwuwzCEu9VEiU9lV75Y.jpg",
    genre_ids: [28],
    id: 645788,
    original_language: "en",
    original_title: "The Protégé",
    overview:
      "Rescued as a child by the legendary assassin Moody and trained in the family business, Anna is the world’s most skilled contract killer. When Moody, the man who was like a father to her and taught her everything she needs to know about trust and survival, is brutally killed, Anna vows revenge. As she becomes entangled with an enigmatic killer whose attraction to her goes way beyond cat and mouse, their confrontation turns deadly and the loose ends of a life spent killing will weave themselves ever tighter.",
    popularity: 139.991,
    poster_path: "/o9FY8N5c8CXf22q8s4CmRRjAQJx.jpg",
    release_date: "2021-08-19",
    title: "The Protégé",
    video: false,
    vote_average: 6.7,
    vote_count: 510,
  },
  {
    adult: false,
    backdrop_path: "/t9K8ycUBCplWiICDOKRNRYcEH9e.jpg",
    genre_ids: [16, 28, 12, 9648],
    id: 810693,
    original_language: "ja",
    original_title: "Jujutsu Kaisen 0",
    overview:
      "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
    popularity: 131.865,
    poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
    release_date: "2021-02-24",
    title: "Jujutsu Kaisen 0",
    video: false,
    vote_average: 7.3,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/4KLlHifB1kgMtWl3YnY8JinOj65.jpg",
    genre_ids: [18],
    id: 777270,
    original_language: "en",
    original_title: "Belfast",
    overview:
      "Buddy is a young boy on the cusp of adolescence, whose life is filled with familial love, childhood hijinks, and a blossoming romance. Yet, with his beloved hometown caught up in increasing turmoil, his family faces a momentous choice: hope the conflict will pass or leave everything they know behind for a new life.",
    popularity: 95.503,
    poster_path: "/3mInLZyPOVLsZRsBwNHi3UJXXnm.jpg",
    release_date: "2021-11-11",
    title: "Belfast",
    video: false,
    vote_average: 7,
    vote_count: 232,
  },
  {
    adult: false,
    backdrop_path: "/w81qHqr1CdbdRco8jpmu6lXMqyk.jpg",
    genre_ids: [18],
    id: 766798,
    original_language: "es",
    original_title: "Madres paralelas",
    overview:
      "Two unmarried women who have become pregnant by accident and are about to give birth meet in a hospital room: Janis, middle-aged, unrepentant and happy; Ana, a teenager, remorseful and frightened.",
    popularity: 95.63,
    poster_path: "/gDaxYkYNbHuM2VlUazbcpnFZB6d.jpg",
    release_date: "2021-10-08",
    title: "Parallel Mothers",
    video: false,
    vote_average: 6.8,
    vote_count: 359,
  },
  {
    adult: false,
    backdrop_path: "/8T7SS4jU7TmtqrUr45JgZASCTUP.jpg",
    genre_ids: [18, 35],
    id: 626735,
    original_language: "en",
    original_title: "Dog",
    overview:
      "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
    popularity: 90.066,
    poster_path: "/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg",
    release_date: "2022-02-17",
    title: "Dog",
    video: false,
    vote_average: 7.9,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: "/6jRHaYJyje5RNS3L353udrPU3ME.jpg",
    genre_ids: [18],
    id: 554230,
    original_language: "en",
    original_title: "The Lost Daughter",
    overview:
      "A woman's seaside vacation takes a dark turn when her obsession with a young mother forces her to confront secrets from her past.",
    popularity: 87.094,
    poster_path: "/t1oLNRFixpFOVsyz1HCqCUW3wiW.jpg",
    release_date: "2021-12-16",
    title: "The Lost Daughter",
    video: false,
    vote_average: 6.6,
    vote_count: 374,
  },
  {
    adult: false,
    backdrop_path: "/fdE7pXaGyaFI39dy3Fg59FSauNr.jpg",
    genre_ids: [18],
    id: 716612,
    original_language: "en",
    original_title: "Spencer",
    overview:
      "During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana decides to leave her marriage to Prince Charles.",
    popularity: 88.761,
    poster_path: "/7GcqdBKaMM9BWXWN07BirBMkcBF.jpg",
    release_date: "2021-11-04",
    title: "Spencer",
    video: false,
    vote_average: 7.2,
    vote_count: 546,
  },
  {
    adult: false,
    backdrop_path: "/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg",
    genre_ids: [16, 10751, 14],
    id: 520946,
    original_language: "en",
    original_title: "100% Wolf",
    overview:
      "Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.",
    popularity: 77.074,
    poster_path: "/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg",
    release_date: "2020-06-26",
    title: "100% Wolf",
    video: false,
    vote_average: 5.9,
    vote_count: 219,
  },
  {
    adult: false,
    backdrop_path: "/e8JXiXBrjlPICy0v16TPylmXSr7.jpg",
    genre_ids: [27],
    id: 573680,
    original_language: "en",
    original_title: "The Banishing",
    overview:
      "In the 1930s, a young reverend and his family are forced to confront their worst fears when they discover their new home holds a horrifying secret.",
    popularity: 73.562,
    poster_path: "/xD9mc8JCVXA8T8u4Od7qOUBuGH4.jpg",
    release_date: "2021-04-29",
    title: "The Banishing",
    video: false,
    vote_average: 5.5,
    vote_count: 56,
  },
  {
    adult: false,
    backdrop_path: "/l0vpgXSHuXNEeqbcOosGvdFk603.jpg",
    genre_ids: [12, 10751],
    id: 780382,
    original_language: "en",
    original_title: "Le Loup et le Lion",
    overview:
      "After her grandfather's death, 20-year-old Alma decides to go back to her childhood home - a little island in the heart of the majestic Canadian forest. Whilst there, she rescues two helpless cubs: a wolf and a lion. They forge an inseparable bond, but their world soon collapses as the forest ranger discovers the animals and takes them away. The two cub brothers must now embark on a treacherous journey across Canada to be reunited with one another and Alma once more.",
    popularity: 64.481,
    poster_path: "/aSRvK4kLJORBrVdlFn2wrGx8XPv.jpg",
    release_date: "2021-10-13",
    title: "The Wolf and the Lion",
    video: false,
    vote_average: 7.2,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: "/tULzz524DuvMxnAuQJpo8dk0EvJ.jpg",
    genre_ids: [28, 53],
    id: 823625,
    original_language: "en",
    original_title: "Blacklight",
    overview:
      "Travis Block, a shadowy Government agent who specializes in removing operatives whose covers have been exposed, uncovers a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
    popularity: 73.531,
    poster_path: "/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg",
    release_date: "2022-02-10",
    title: "Blacklight",
    video: false,
    vote_average: 5.3,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: "/4Pog7brcDaTv7BEG2mxuGcMUjdJ.jpg",
    genre_ids: [27, 35, 10402],
    id: 895744,
    original_language: "en",
    original_title: "Studio 666",
    overview:
      "Legendary rock band Foo Fighters move into an Encino mansion steeped in grisly rock and roll history to record their much anticipated 10th album. Once in the house, Dave Grohl finds himself grappling with supernatural forces that threaten both the completion of the album and the lives of the band.",
    popularity: 49.607,
    poster_path: "/9OHrpaAfN8CkCYjzwqczgEN9VxV.jpg",
    release_date: "2022-02-24",
    title: "Studio 666",
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/i8ung7plwLlpUBltgn3jD6blV80.jpg",
    genre_ids: [16, 35, 10751],
    id: 778810,
    original_language: "en",
    original_title: "Fireheart",
    overview:
      "The film explores the world of firefighters in 1920s New York City and tells the story of a 16-year-old girl who will have to become a hero in order to save her city.",
    popularity: 59.755,
    poster_path: "/nmD0vZk8jQg1Suhs0iv9cj0xdtZ.jpg",
    release_date: "2022-02-02",
    title: "Fireheart",
    video: false,
    vote_average: 6.6,
    vote_count: 17,
  },
];

export const topRatedTV = [
  {
    backdrop_path: "/7q448EVOnuE3gVAx24krzO7SNXM.jpg",
    first_air_date: "2021-09-03",
    genre_ids: [10764],
    id: 130392,
    name: "The D'Amelio Show",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The D'Amelio Show",
    overview:
      "From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.",
    popularity: 24.564,
    poster_path: "/z0iCS5Znx7TeRwlYSd4c01Z0lFx.jpg",
    vote_average: 9.4,
    vote_count: 2639,
  },
  {
    backdrop_path: null,
    first_air_date: "2004-05-10",
    genre_ids: [16, 35],
    id: 100,
    name: "I Am Not an Animal",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "I Am Not an Animal",
    overview:
      "I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upside down when they are liberated by animal rights activists.",
    popularity: 10.24,
    poster_path: "/qG59J1Q7rpBc1dvku4azbzcqo8h.jpg",
    vote_average: 9.2,
    vote_count: 692,
  },
  {
    backdrop_path: "/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg",
    first_air_date: "2021-11-06",
    genre_ids: [16, 10765, 10759, 18],
    id: 94605,
    name: "Arcane",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    popularity: 266.849,
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    vote_average: 9.1,
    vote_count: 1791,
  },
  {
    backdrop_path: "/7gbmM2NWcqZONbp65HUWDf4wr0Q.jpg",
    first_air_date: "2019-07-12",
    genre_ids: [16, 18],
    id: 88040,
    name: "Given",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ギヴン",
    overview:
      "Tightly clutching his Gibson guitar, Mafuyu Satou steps out of his dark apartment to begin another day of his high school life. While taking a nap in a quiet spot on the gymnasium staircase, he has a chance encounter with fellow student Ritsuka Uenoyama, who berates him for letting his guitar's strings rust and break. Noticing Uenoyama's knowledge of the instrument, Satou pleads for him to fix it and to teach him how to play. Uenoyama eventually agrees and invites him to sit in on a jam session with his two band mates: bassist Haruki Nakayama and drummer Akihiko Kaji.",
    popularity: 48.095,
    poster_path: "/pdDCcAq8RNSZNk81PXYoHNUPHjn.jpg",
    vote_average: 9,
    vote_count: 587,
  },
  {
    backdrop_path: "/c8dm74uPCMA27iKAR1WnHKTsI9h.jpg",
    first_air_date: "2015-08-01",
    genre_ids: [10764],
    id: 77696,
    name: "Run BTS!",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "달려라 방탄!",
    overview:
      "Run BTS! is a South Korean show by the boy band BTS. The show is all about BTS doing activities, challenges and lots more.",
    popularity: 28.731,
    poster_path: "/xxv8Ibs8Anni6qrWkAf60rDsPCu.jpg",
    vote_average: 9,
    vote_count: 244,
  },
  {
    backdrop_path: "/qSgBzXdu6QwVVeqOYOlHolkLRxZ.jpg",
    first_air_date: "2019-01-09",
    genre_ids: [16, 10759, 10765, 18],
    id: 83095,
    name: "The Rising of the Shield Hero",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "盾の勇者の成り上がり",
    overview:
      "Iwatani Naofumi was summoned into a parallel world along with 3 other people to become the world's Heroes. Each of the heroes respectively equipped with their own legendary equipment when summoned, Naofumi received the Legendary Shield as his weapon. Due to Naofumi's lack of charisma and experience he's labeled as the weakest, only to end up betrayed, falsely accused, and robbed by on the third day of adventure. Shunned by everyone from the king to peasants, Naofumi's thoughts were filled with nothing but vengeance and hatred. Thus, his destiny in a parallel World begins...",
    popularity: 51.173,
    poster_path: "/hm7AAWOMNxGzpGolgzNATgnyQbb.jpg",
    vote_average: 9,
    vote_count: 778,
  },
  {
    backdrop_path: "/hqFaSNICeh0Y3Hp0gtEIzDBmUVo.jpg",
    first_air_date: "2020-08-19",
    genre_ids: [10764],
    id: 106600,
    name: "BTS In the SOOP",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "In the SOOP BTS편",
    overview:
      "'In the SOOP BTS ver.' is a reality show, portraying BTS members' everyday life, relaxation, and everything in between, away from the city life. A time of freedom and healing in a place for BTS, and BTS only.",
    popularity: 15.544,
    poster_path: "/eBsIEKqLMtktw2jpFPa9WTuGyPN.jpg",
    vote_average: 8.9,
    vote_count: 270,
  },
  {
    backdrop_path: "/uAjMQlbPkVHmUahhCouANlHSDW2.jpg",
    first_air_date: "2019-01-11",
    genre_ids: [16, 9648, 10765, 10759, 18],
    id: 83097,
    name: "The Promised Neverland",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "約束のネバーランド",
    overview:
      'Surrounded by a forest and a gated entrance, the Grace Field House is inhabited by orphans happily living together as one big family, looked after by their "Mama," Isabella. Although they are required to take tests daily, the children are free to spend their time as they see fit, usually playing outside, as long as they do not venture too far from the orphanage — a rule they are expected to follow no matter what. However, all good times must come to an end, as every few months, a child is adopted and sent to live with their new family... never to be heard from again.However, the three oldest siblings have their suspicions about what is actually happening at the orphanage, and they are about to discover the cruel fate that awaits the children living at Grace Field, including the twisted nature of their beloved Mama.',
    popularity: 85.89,
    poster_path: "/oBgRCpAbtMpk1v8wfdsIph7lPQE.jpg",
    vote_average: 8.9,
    vote_count: 764,
  },
  {
    backdrop_path: "/ohOrfdh80HVY5QBD8kV2FYYSVwF.jpg",
    first_air_date: "2021-01-10",
    genre_ids: [16, 10759],
    id: 110309,
    name: "SK8 the Infinity",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "SK∞ エスケーエイト",
    overview:
      '"S" is a dangerous, top secret, no-holds-barred downhill skateboarding race down an abandoned mine. When avid skateboarder Reki takes Langa to the mountain where "S" is held, Langa, who\'s never been on a skateboard in his life, finds himself sucked into the world of "S", and…?!',
    popularity: 91.433,
    poster_path: "/ksb6QlSCsRLr3MNmxc8ojOOLK6V.jpg",
    vote_average: 8.9,
    vote_count: 191,
  },
  {
    backdrop_path: "/5nubzpKcNjV7zDwHkAV0J7yAJlH.jpg",
    first_air_date: "2021-07-01",
    genre_ids: [18],
    id: 125910,
    name: "Young Royals",
    origin_country: ["SE"],
    original_language: "sv",
    original_name: "Young Royals",
    overview:
      "Prince Wilhelm adjusts to life at his prestigious new boarding school, Hillerska, but following his heart proves more challenging than anticipated.",
    popularity: 44.167,
    poster_path: "/6CHznbr0BF78ar16zJwTVRYLLOX.jpg",
    vote_average: 8.9,
    vote_count: 570,
  },
  {
    backdrop_path: "/2f8OLO6UYp78dIQMs0oi7ja15Bl.jpg",
    first_air_date: "2010-04-02",
    genre_ids: [16, 35, 18],
    id: 65648,
    name: "Maid Sama!",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "会長はメイド様！",
    overview:
      "Misaki Ayuzawa is the first female student council president at a once all-boys school turned co-ed. She rules the school with strict discipline demeanor. But she has a secret—she works at a maid cafe due to her families circumstances. One day the popular A-student and notorious heart breaker Takumi Usui finds out her secret and makes a deal with her to keep it hush from the school in exchange for spending some time with him.",
    popularity: 44.895,
    poster_path: "/igkn0M1bgMeATz59LShvVxZNdVd.jpg",
    vote_average: 8.9,
    vote_count: 433,
  },
  {
    backdrop_path: "/1ejS56lC8db62IKVj1pTQlfAEQy.jpg",
    first_air_date: "2018-09-13",
    genre_ids: [10759, 16, 18, 10751],
    id: 123566,
    name: "Metal Family",
    origin_country: ["RU"],
    original_language: "ru",
    original_name: "Metal Family",
    overview:
      "Metal Family follows the daily lives of Glam and Victoria, two metal fans that fell in love and had two children together, Dee and Heavy.",
    popularity: 38.533,
    poster_path: "/yovTSLBdNjXIVo8CPaPWFE5NcAw.jpg",
    vote_average: 8.9,
    vote_count: 283,
  },
  {
    backdrop_path: "/ci7jTekDFEx6U48XUCl3vBMdrns.jpg",
    first_air_date: "2018-07-06",
    genre_ids: [10759, 18, 9648, 16],
    id: 80564,
    name: "Banana Fish",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "バナナフィッシュ",
    overview:
      "Nature made Ash Lynx beautiful; nurture made him a cold ruthless killer. A runaway brought up as the adopted heir and sex toy of \"Papa\" Dino Golzine, Ash, now at the rebellious age of seventeen, forsakes the kingdom held out by the devil who raised him. But the hideous secret that drove Ash's older brother mad in Vietnam has suddenly fallen into Papa's insatiably ambitious hands—and it's exactly the wrong time for Eiji Okamura, a pure-hearted young photographer from Japan, to make Ash Lynx's acquaintance...",
    popularity: 64.793,
    poster_path: "/1UV5di9UIXwrpCW3xQ4RNli5hEV.jpg",
    vote_average: 8.9,
    vote_count: 662,
  },
  {
    backdrop_path: "/sWghoJDqMRHDnkmk7fr3By5XPnf.jpg",
    first_air_date: "2019-10-05",
    genre_ids: [16, 35, 10765],
    id: 91801,
    name: "Welcome to Demon School! Iruma-kun",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "魔入りました！入間くん",
    overview:
      "Fourteen-year-old Suzuki Iruma has just been abandoned and sold to a demon by his irresponsible parents! Surprisingly, the next thing he knows he's living with the demon who has adopted him as his new grandson, and has been transferred into a school in the demon world where his new \"demon\" grandfather works as the principal. Thus begins the cowardly Iruma-kun's extraordinary school life among the otherworldly as he faces his true self, takes on challenges, and rises to become someone great.",
    popularity: 77.663,
    poster_path: "/aed6I1EMR4Lbk8bdikWrndbn5Og.jpg",
    vote_average: 8.9,
    vote_count: 167,
  },
  {
    backdrop_path: "/x6jWDL4H9TaBLGEvyej0qKiirBU.jpg",
    first_air_date: "2014-10-10",
    genre_ids: [16, 35, 18],
    id: 61663,
    name: "Your Lie in April",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "四月は君の嘘",
    overview:
      "Kousei Arima was a genius pianist until his mother's sudden death took away his ability to play. Each day was dull for Kousei. But, then he meets a violinist named Kaori Miyazono who has an eccentric playing style. Can the heartfelt sounds of the girl's violin lead the boy to play the piano again?",
    popularity: 61.478,
    poster_path: "/IGbeFv5Ji4W0x530JcSHiQpamY.jpg",
    vote_average: 8.9,
    vote_count: 642,
  },
  {
    backdrop_path: "/rXXC22YUo31QfOsavy0jUbqdxFc.jpg",
    first_air_date: "2014-12-09",
    genre_ids: [10765, 10759, 16],
    id: 73055,
    name: "Attack on Titan: No Regrets",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "進撃の巨人 悔いなき選択",
    overview:
      "Many years before becoming the famed captain of the Survey Corps, a young Levi struggles to survive in the capital's garbage dump, the Underground. As the boss of his own criminal operation, Levi attempts to get by with meager earnings while aided by fellow criminals, Isabel Magnolia and Farlan Church. With little hope for the future, Levi accepts a deal from the anti-expedition faction leader Nicholas Lobov, who promises the trio citizenship aboveground if they are able to successfully assassinate Erwin Smith, a squad leader of the Survey Corps.",
    popularity: 117.729,
    poster_path: "/xGdz67d5WHIU7kIqVHO2TxIpmhZ.jpg",
    vote_average: 8.9,
    vote_count: 2014,
  },
  {
    backdrop_path: "/dwEkNoGFZJWqiwJrnzVfmtmVhfU.jpg",
    first_air_date: "2019-01-11",
    genre_ids: [16, 35, 18],
    id: 84669,
    name: "The Quintessential Quintuplets",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "五等分の花嫁",
    overview:
      "Fuutarou Uesugi is a poor, antisocial ace student who one day meets the rich transfer student Itsuki Nakano. They argue but when Uesugi realizes he is to be her tutor, he tries to get on better terms. While trying to do so he meets four other girls.",
    popularity: 106.011,
    poster_path: "/mrahUSmFjae8UHtlOcZ58ytmAGu.jpg",
    vote_average: 8.9,
    vote_count: 498,
  },
  {
    backdrop_path: "/T2Oi1KTOOVhHygBK99yX4QHZg9.jpg",
    first_air_date: "2021-02-20",
    genre_ids: [10759, 35, 18],
    id: 117376,
    name: "Vincenzo",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "빈센조",
    overview:
      "Vincenzo Cassano is an Italian lawyer and Mafia consigliere who moves back to Korea due to a conflict within his organization. He ends up crossing paths with a sharp-tongued lawyer named Cha-young, and the two join forces in using villainous methods to take down villains who cannot be punished by the law.",
    popularity: 77.347,
    poster_path: "/dvXJgEDQXhL9Ouot2WkBHpQiHGd.jpg",
    vote_average: 8.9,
    vote_count: 453,
  },
  {
    backdrop_path: "/zEQz64k0WD8SLd97MDCgauAsXQn.jpg",
    first_air_date: "2010-04-23",
    genre_ids: [16, 10759, 10762, 10751, 9648],
    id: 32118,
    name: "Generator Rex",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Generator Rex",
    overview:
      "Generator Rex, an average teenager with the ability to turn his body into amazing machines, helps the secret organization Providence save the world from the nanite threat and dangerous EVO monsters.",
    popularity: 38.57,
    poster_path: "/fL7S22SWWOjJTgHEkk68VZ4Z8RO.jpg",
    vote_average: 8.9,
    vote_count: 253,
  },
  {
    backdrop_path: "/mWwWhDiQWONiSS4Go12TTjNw0E5.jpg",
    first_air_date: "2016-10-06",
    genre_ids: [16, 35, 18],
    id: 68129,
    name: "Yuri!!! on Ice",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ユーリ!!! on ICE",
    overview:
      "Yūri Katsuki carried all of Japan's hopes on his shoulders to win at the Gran Prix Finale ice skating competition, but suffered a crushing defeat. He returns home to Kyushu and half feels like he wants to retire, and half feels like he wants to continue ice skating. Suddenly the five-time consecutive world championship ice skater Victor Nikiforov appears before him with Yuri Plisetsky, a young Russian figure skater who is already defeating his seniors. Victor and both Yuris take up the challenge on an unprecedented Gran Prix series.",
    popularity: 28.774,
    poster_path: "/oKVFf2uNCLMsovWBxAW14MmhHUm.jpg",
    vote_average: 8.8,
    vote_count: 465,
  },
];

export const popularTV = [
  {
    backdrop_path: "/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg",
    first_air_date: "2019-06-16",
    genre_ids: [18],
    id: 85552,
    name: "Euphoria",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Euphoria",
    overview:
      "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
    popularity: 4556.207,
    poster_path: "/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg",
    vote_average: 8.4,
    vote_count: 6964,
  },
  {
    backdrop_path: "/4g5gK5eGWZg8swIZl6eX2AoJp8S.jpg",
    first_air_date: "2003-10-21",
    genre_ids: [18],
    id: 11250,
    name: "Pasión de gavilanes",
    origin_country: ["CO"],
    original_language: "es",
    original_name: "Pasión de gavilanes",
    overview:
      "The Reyes-Elizondo's idyllic lives are shattered by a murder charge against Eric and León.",
    popularity: 5604.281,
    poster_path: "/lWlsZIsrGVWHtBeoOeLxIKDd9uy.jpg",
    vote_average: 7.7,
    vote_count: 1697,
  },
  {
    backdrop_path: "/8Xs20y8gFR0W9u8Yy9NKdpZtSu7.jpg",
    first_air_date: "2022-01-28",
    genre_ids: [18, 10765],
    id: 99966,
    name: "All of Us Are Dead",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "지금 우리 학교는",
    overview:
      "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out — or turn into one of the rabid infected.",
    popularity: 2440.504,
    poster_path: "/ze4lhw0oLBHYmlM2KuZjBg0Sq6H.jpg",
    vote_average: 8.7,
    vote_count: 1433,
  },
  {
    backdrop_path: "/ctxm191q5o3axFzQsvNPlbKoSYv.jpg",
    first_air_date: "2022-01-13",
    genre_ids: [10759, 10765, 18],
    id: 110492,
    name: "Peacemaker",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Peacemaker",
    overview:
      "The continuing story of Peacemaker – a compellingly vainglorious man who believes in peace at any cost, no matter how many people he has to kill to get it – in the aftermath of the events of “The Suicide Squad.”",
    popularity: 1825.553,
    poster_path: "/hE3LRZAY84fG19a18pzpkZERjTE.jpg",
    vote_average: 8.6,
    vote_count: 1193,
  },
  {
    backdrop_path: null,
    first_air_date: "1972-09-04",
    genre_ids: [],
    id: 2051,
    name: "The Price Is Right",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Price Is Right",
    overview:
      "Come on down! The Price Is Right features a wide variety of games and contests with the same basic challenge: Guess the prices of everyday (or not-quite-everyday) retail items. ",
    popularity: 1791.434,
    poster_path: "/6m4uYFAJwkanZXd0n0HUQ0lYHLl.jpg",
    vote_average: 6.2,
    vote_count: 50,
  },
  {
    backdrop_path: "/7jHD9rcLUpDv3mvsSoKtYxItMwK.jpg",
    first_air_date: "2019-09-01",
    genre_ids: [18],
    id: 93411,
    name: "Bride of Beirut",
    origin_country: ["LB"],
    original_language: "ar",
    original_name: "عروس بيروت",
    overview:
      "Thuraya a simple girl living a modest life with her aunt, her life changes forever when she meets Faress a young and ambitious young man.",
    popularity: 1022.332,
    poster_path: "/v85weOiO0S0navaklsCqisgKN3B.jpg",
    vote_average: 4,
    vote_count: 4,
  },
  {
    backdrop_path: "/yfXSvNfF43S0cxpxCEKaU17yZ64.jpg",
    first_air_date: "1983-09-19",
    genre_ids: [10751],
    id: 2778,
    name: "Wheel of Fortune",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Wheel of Fortune",
    overview:
      "This game show sees contestants solve word puzzles, similar to those used in Hangman, to win cash and prizes determined by spinning a giant carnival wheel.",
    popularity: 1439.523,
    poster_path: "/2fvAIyVfFHQdhJ7OsJWuMlF7836.jpg",
    vote_average: 6.9,
    vote_count: 45,
  },
  {
    backdrop_path: "/vhEtBjbxLMlPTPCS6TGk0WLo9C8.jpg",
    first_air_date: "2021-09-09",
    genre_ids: [10764],
    id: 132712,
    name: "Secret Story: The House of Secrets",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Secret Story: La casa de los secretos",
    overview: "",
    popularity: 1412.276,
    poster_path: "/rucYOgpymV2gAvyJUVK1awLTOcH.jpg",
    vote_average: 3,
    vote_count: 2,
  },
  {
    backdrop_path: "/r7zUXadc1saFFSWz8lbUx7q9bkG.jpg",
    first_air_date: "2010-10-31",
    genre_ids: [10759, 18, 10765],
    id: 1402,
    name: "The Walking Dead",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    popularity: 1296.727,
    poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    vote_average: 8.1,
    vote_count: 12581,
  },
  {
    backdrop_path: "/l6zdjUDOaklBWfxqa7AtbLr2EnA.jpg",
    first_air_date: "2021-12-13",
    genre_ids: [10751, 35, 18],
    id: 135753,
    name: "Love Twist",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "사랑의 꽈배기",
    overview:
      "A drama depicting a sweet twist in love between the parents and children of three families around the love of two main characters.",
    popularity: 1371.044,
    poster_path: "/5bTF522eYn6g6r7aYqFpTZzmQq6.jpg",
    vote_average: 4.5,
    vote_count: 2,
  },
  {
    backdrop_path: "/q9o7VEHX0O9oixdIa6uT0v5lu3S.jpg",
    first_air_date: "2022-01-28",
    genre_ids: [18],
    id: 156568,
    name: "A Lifelong Journey",
    origin_country: ["CN"],
    original_language: "zh",
    original_name: "人世间",
    overview: "",
    popularity: 1317.034,
    poster_path: "/u5LOe5BMtNPticKT9fAzTkxSlst.jpg",
    vote_average: 6.7,
    vote_count: 3,
  },
  {
    backdrop_path: "/s0L56Zv3NVH1kZTrLfTQ2kwvQeD.jpg",
    first_air_date: "2022-01-24",
    genre_ids: [18],
    id: 125030,
    name: "The Broken Marriage Vow",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "The Broken Marriage Vow",
    overview:
      "A seemingly perfect home gets shattered by broken trust and infidelity, bringing forth catastrophic effects into the lives of the couple, their son, and everyone else involved. This is a story about a woman scorned.",
    popularity: 1370.726,
    poster_path: "/gBJIKWkI90L57ky6EUzQGE6wWpJ.jpg",
    vote_average: 5.5,
    vote_count: 2,
  },
  {
    backdrop_path: "/gIApbx2ffXVhJb2D4tiEx2b06nl.jpg",
    first_air_date: "2005-03-27",
    genre_ids: [18],
    id: 1416,
    name: "Grey's Anatomy",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    popularity: 937.661,
    poster_path: "/zPIug5giU8oug6Xes5K1sTfQJxY.jpg",
    vote_average: 8.3,
    vote_count: 7669,
  },
  {
    backdrop_path: "/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg",
    first_air_date: "2021-12-29",
    genre_ids: [10759, 10765],
    id: 115036,
    name: "The Book of Boba Fett",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Book of Boba Fett",
    overview:
      "Legendary bounty hunter Boba Fett and mercenary Fennec Shand must navigate the galaxy’s underworld when they return to the sands of Tatooine to stake their claim on the territory once ruled by Jabba the Hutt and his crime syndicate.",
    popularity: 1072.863,
    poster_path: "/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg",
    vote_average: 8.3,
    vote_count: 1122,
  },
  {
    backdrop_path: "/r8CGqB8IJNbA1IruHWquS7YttNB.jpg",
    first_air_date: "1995-10-23",
    genre_ids: [10766],
    id: 966,
    name: "Hollyoaks",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Hollyoaks",
    overview:
      "The daily soap that follows the loves, lives and misdemeanours of a group of people living in the Chester village of Hollyoaks where anything could, and frequently does, happen...",
    popularity: 1172.588,
    poster_path: "/bpmLMZP3M1vLujPqHnOTnKVjRJY.jpg",
    vote_average: 5.1,
    vote_count: 37,
  },
  {
    backdrop_path: "/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    first_air_date: "2013-09-12",
    genre_ids: [18, 80],
    id: 60574,
    name: "Peaky Blinders",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Peaky Blinders",
    overview:
      "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.",
    popularity: 968.283,
    poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    vote_average: 8.6,
    vote_count: 5398,
  },
  {
    backdrop_path: "/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg",
    first_air_date: "2016-01-25",
    genre_ids: [80, 10765],
    id: 63174,
    name: "Lucifer",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    popularity: 942.471,
    poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    vote_average: 8.5,
    vote_count: 11545,
  },
  {
    backdrop_path: "/fiKQKFsjahOr8qj7QsUUHO9E70t.jpg",
    first_air_date: "2022-02-11",
    genre_ids: [18],
    id: 95665,
    name: "Inventing Anna",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Inventing Anna",
    overview:
      "A journalist with a lot to prove investigates the case of Anna Delvey, the Instagram-legendary German heiress who stole the hearts of New York’s social scene – and stole their money as well.",
    popularity: 878.81,
    poster_path: "/jzCnl9wACp0eUMa3IG5e0aSJIXD.jpg",
    vote_average: 7.1,
    vote_count: 40,
  },
  {
    backdrop_path: "/l8WwTX2o16n3MbD6Yz2NNYKOt8i.jpg",
    first_air_date: "2019-09-09",
    genre_ids: [10764],
    id: 93364,
    name: "Judge Jerry",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Judge Jerry",
    overview:
      "Jerry Springer is now moving from the stage to behind the bench in this new court show where he will be presiding cases.",
    popularity: 915.493,
    poster_path: "/54iJ45FF2m9jNsioGltHypVlvKh.jpg",
    vote_average: 5.3,
    vote_count: 4,
  },
  {
    backdrop_path: "/41yaWnIT8AjIHiULHtTbKNzZTjc.jpg",
    first_air_date: "2014-10-07",
    genre_ids: [18, 10765],
    id: 60735,
    name: "The Flash",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Flash",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    popularity: 903.855,
    poster_path: "/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
    vote_average: 7.8,
    vote_count: 9333,
  },
];
